name: Python Package using Conda

on: 
  pull_request:
    branches: [master, main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }}-Python${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Which conda/python
        run: |
          conda --version
          python --version
      - name: Install dependencies
        run: |
          pip install .[templates,test]
      - name: pip list
        run: |
          pip list
      - name: Test with pytest and build coverage report
        run: |
          pytest -s
